"""agregar job_position_permissions

Revision ID: 991591509538
Revises: d46f351a76e1
Create Date: 2026-07-11 11:38:47.287457
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '991591509538'
down_revision: str | None = 'd46f351a76e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_position_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_position_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_position_id', 'permission_code', name='uq_job_position_permission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_position_permissions')
    # ### end Alembic commands ###
