"""agregar columna is_local a sync_stations

Revision ID: b562683b3ccf
Revises: 7d3d00ef46d1
Create Date: 2026-07-10 10:16:02.341846
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b562683b3ccf'
down_revision: str | None = '7d3d00ef46d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_stations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_local', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_stations', schema=None) as batch_op:
        batch_op.drop_column('is_local')

    # ### end Alembic commands ###
