"""agregar job_areas y job_positions

Revision ID: f976ce673f36
Revises: b562683b3ccf
Create Date: 2026-07-10 23:10:44.615512
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f976ce673f36'
down_revision: str | None = 'b562683b3ccf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('job_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_areas_uuid'), ['uuid'], unique=True)

    op.create_table('job_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['job_areas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'name', name='uq_job_position_area_name')
    )
    with op.batch_alter_table('job_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_positions_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_area_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_position_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_users_job_position_id_job_positions',
            'job_positions', ['job_position_id'], ['id'], ondelete='SET NULL'
        )
        batch_op.create_foreign_key(
            'fk_users_job_area_id_job_areas',
            'job_areas', ['job_area_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_job_area_id_job_areas', type_='foreignkey')
        batch_op.drop_constraint('fk_users_job_position_id_job_positions', type_='foreignkey')
        batch_op.drop_column('job_position_id')
        batch_op.drop_column('job_area_id')

    with op.batch_alter_table('job_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_positions_uuid'))

    op.drop_table('job_positions')
    with op.batch_alter_table('job_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_areas_uuid'))

    op.drop_table('job_areas')
    # ### end Alembic commands ###
